# Generated by Django 3.0 on 2024-02-28 18:28

from django.db import migrations


def forwards(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    Profile = apps.get_model('profiles', 'Profile')

    for old_profile in OldProfile.objects.all():
        Profile.objects.create(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )


def backwards(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    Profile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        # Assurez-vous que cette migration est appliquée après la création des tables pour les nouveaux modèles.
        ('profiles', '0001_initial'),
        # Et après la dernière migration de l'application 'oc_lettings_site'
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

