version: '3.8'

services:
  web:
    build: .
    command: gunicorn oc_lettings_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      SECRET_KEY: ${SECRET_KEY}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
    depends_on:
      - web

volumes:
  static_volume:
    name: static_volume
    driver: local