# Generated by Django 3.0 on 2024-02-28 18:28

from django.db import migrations


def migrate_letting_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    Address = apps.get_model('lettings', 'Address')
    Letting = apps.get_model('lettings', 'Letting')

    address_mapping = {}

    for old_address in OldAddress.objects.all():
        new_address = Address.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        )
        address_mapping[old_address.id] = new_address.id

    for old_letting in OldLetting.objects.all():
        new_letting = Letting.objects.create(
            title=old_letting.title,
            address_id=address_mapping[old_letting.address_id],

        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [

        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_letting_data, backwards),
    ]
